### ISSUE TITLE
PBS Kids app shows as "incompatible" on XBMC.

### ISSUE THREAD

**Issue by zguithues** [conorbranagan/xbmc-plugins#2]
i think the app needs to be updated to support gothem.  Do you think you could take a look at it?  My kids really want to be able to stream the new episodes on there.

Thanks!

**Comment by conorbranagan** [comment]
Hi @zguithues. Thanks for reporting this! I pushed a new version 1.2 to the repo that fixes support of Gotham and also adds some new shows and other small fixes. I've tested it on Gotham on my home mac but let me know if you have anything issues.

**Comment by zguithues** [comment]
Thanks a lot for the quick fix!

I tried to install the updated version, but i only see 1.1 in your repository.  Do i need to wait for things to sync?

**Comment by conorbranagan** [comment]
So I had to do a "force update" on the repo which you can get to with open
the context menu when the repo is highlighted. I'm not sure if there's
another way to be honest.

**Comment by zguithues** [comment]
I hadn't seen that option...  It worked!  Thanks!

My kids love you :)
